# -*- coding: utf-8 -*-
"""db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trXxoHuhoS706ydeTXELxtIoxy87-DBV
"""

!apt-get install sqlite3

import sqlite3

def init_db():
    conn = sqlite3.connect("receipts.db")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS receipts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            raw_text TEXT,
            category TEXT,
            date TEXT,
            amount REAL
        )
    """)
    conn.commit()
    conn.close()

def insert_receipt(raw_text, category, date, amount):
    init_db()
    conn = sqlite3.connect("receipts.db")
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO receipts (raw_text, category, date, amount) VALUES (?, ?, ?, ?)",
        (raw_text, category.strip(), date, amount)
    )
    conn.commit()
    conn.close()

insert_receipt("Big Bazaar", "Groceries", "2025-08-09", 1250.50)
insert_receipt("Amazon", "Electronics", "2025-08-10", 4999.99)
insert_receipt("Big Bazaar - TATA SAMPANN DAL 1KG, FORTUNE OIL 1L", "Groceries", "2025-08-01", 1250.50)
insert_receipt("Amazon - Sony Headphones WH-1000XM4", "Electronics", "2025-08-02", 24990.00)
insert_receipt("Swiggy - Pizza Hut Veggie Supreme", "Food", "2025-08-03", 599.00)
insert_receipt("Flipkart - HP Pavilion Laptop 15", "Electronics", "2025-08-04", 59990.00)
insert_receipt("Uber - Airport Drop", "Transport", "2025-08-05", 450.00)
insert_receipt("Reliance Digital - Samsung Galaxy S23", "Electronics", "2025-08-06", 79999.00)
insert_receipt("Myntra - Nike Running Shoes", "Fashion", "2025-08-07", 4999.00)
insert_receipt("Domino's - Cheese Burst Pizza", "Food", "2025-08-08", 799.00)
insert_receipt("BookMyShow - Oppenheimer IMAX Ticket", "Entertainment", "2025-08-09", 350.00)
insert_receipt("D-Mart - Rice 10KG, Oil 5L", "Groceries", "2025-08-10", 1890.75)
insert_receipt("Zomato - Biryani by Kilo", "Food", "2025-08-11", 899.00)
insert_receipt("Apple Store - MacBook Air M3", "Electronics", "2025-08-12", 114900.00)
insert_receipt("H&M - Denim Jacket", "Fashion", "2025-08-13", 2999.00)
insert_receipt("Spencers - Vegetables & Fruits", "Groceries", "2025-08-14", 745.20)
insert_receipt("MakeMyTrip - Goa Flight Ticket", "Travel", "2025-08-15", 5499.00)
insert_receipt("Tanishq - Gold Chain", "Jewellery", "2025-08-16", 32500.00)
insert_receipt("Metro Shoes - Formal Leather Shoes", "Fashion", "2025-08-17", 3499.00)
insert_receipt("Lifestyle - Perfume Set", "Fashion", "2025-08-18", 1599.00)
insert_receipt("Crossword - Atomic Habits Book", "Books", "2025-08-19", 499.00)
insert_receipt("Samsung Store - 55 Inch QLED TV", "Electronics", "2025-08-20", 75990.00)
insert_receipt("Levi's - Slim Fit Jeans", "Fashion", "2025-08-21", 2799.00)
insert_receipt("Woodland - Trekking Shoes", "Fashion", "2025-08-22", 4499.00)
insert_receipt("Nykaa - Skincare Combo", "Beauty", "2025-08-23", 1899.00)
insert_receipt("Croma - Bluetooth Speaker", "Electronics", "2025-08-24", 4990.00)
insert_receipt("Pantaloons - Summer Dress", "Fashion", "2025-08-25", 1799.00)
insert_receipt("Haldiram's - Snacks & Sweets", "Food", "2025-08-26", 1090.00)
insert_receipt("Tata Cliq - Smartwatch", "Electronics", "2025-08-27", 8999.00)
insert_receipt("PVR Cinemas - Barbie Movie Ticket", "Entertainment", "2025-08-28", 300.00)
insert_receipt("Cafe Coffee Day - Cappuccino & Sandwich", "Food", "2025-08-29", 350.00)
insert_receipt("Ola - Office Ride", "Transport", "2025-08-30", 220.00)
insert_receipt("Paytm Mall - Wireless Mouse", "Electronics", "2025-08-31", 799.00)
insert_receipt("Westside - Formal Shirt", "Fashion", "2025-09-01", 1299.00)
insert_receipt("Burger King - Whopper Meal", "Food", "2025-09-02", 299.00)
insert_receipt("Pepperfry - Study Table", "Furniture", "2025-09-03", 5999.00)
insert_receipt("Urban Ladder - Sofa Set", "Furniture", "2025-09-04", 28990.00)
insert_receipt("Decathlon - Gym Bag", "Sports", "2025-09-05", 899.00)
insert_receipt("Adidas - Sports T-shirt", "Fashion", "2025-09-06", 1499.00)
insert_receipt("Starbucks - Latte & Brownie", "Food", "2025-09-07", 550.00)
insert_receipt("FirstCry - Baby Diapers", "Baby Care", "2025-09-08", 750.00)
insert_receipt("Vijay Sales - Air Conditioner", "Electronics", "2025-09-09", 34990.00)
insert_receipt("FabIndia - Cotton Kurta", "Fashion", "2025-09-10", 1999.00)
insert_receipt("Big Basket - Monthly Groceries", "Groceries", "2025-09-11", 4350.00)
insert_receipt("Bata - Casual Sneakers", "Fashion", "2025-09-12", 1899.00)
insert_receipt("Titan - Analog Watch", "Accessories", "2025-09-13", 6499.00)
insert_receipt("Shoppers Stop - Handbag", "Fashion", "2025-09-14", 2999.00)
insert_receipt("Columbia Sportswear - Jacket", "Fashion", "2025-09-15", 6999.00)
insert_receipt("Chumbak - Coffee Mug Set", "Home Decor", "2025-09-16", 999.00)
insert_receipt("Fastrack - Sunglasses", "Accessories", "2025-09-17", 1799.00)
insert_receipt("IKEA - Desk Lamp", "Home Decor", "2025-09-18", 1290.00)

from google.colab import files
files.download('receipts.db')

